version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CookBooked
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: server/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server/scripts/application_start.sh
      timeout: 300
      runas: root
